manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: george-norton
      url-base: https://github.com/george-norton
    - name: void-veritas
      url-base: https://github.com/void-veritas
    - name: carrefinho
      url-base: https://github.com/carrefinho

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: maxtouch-zephyr-module
      remote: void-veritas  # DEBUG: forked from george-norton with diagnostic logging
      revision: main

    - name: prospector-zmk-module
      remote: carrefinho
      revision: core/zephyr-4-1

  self:
    path: config
